name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-latest
    container:
      image: pseudomuto/protoc-gen-doc
      volumes:
        - out:docs/
        - protos:beer.proto
    steps:
      - name: protoc-gen-doc 
        run: echo build docs.
        
       
#     - name: protoc-gen-doc
#       uses: ./.github/actions/protoc-gen-doc
#       with:
#         out: 'docs'
#         protos: 'beer.proto'
      

